apiVersion: apps/v1
kind: Deployment
metadata:
  name:  react-app
  labels:
    app:  react-app
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  react-app
    spec:
      containers:
      - name:  react-app
        image:  qqbbixz/gitops-ci:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  react-app
      restartPolicy: Always